version: '3.9'

services:
  pocketbase:
    build: ./build/pocketbase
    container_name: pocketbase
    command: --dir "/pb/pb_data" --http "0.0.0.0:8090"
    restart: always
    volumes:
      - "./data/pocketbase:/pb/pb_data"
    networks:
      - default

  nginx:
    image: nginx:1.24.0-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/ssl:ro
      - ./logs:/var/log/nginx
      - ./templates:/etc/nginx/templates
    environment:
      - NGINX_POCKETBASE_DOMAIN=pb.tana.moe
    networks:
      - default

networks:
  default:
    name: default-network
    driver: bridge
