version: '3.9'

services:
  pocketbase:
    build: ./config/pocketbase
    container_name: pocketbase
    restart: always
    volumes:
      - "./data/pocketbase:/pb/pb_data"
    networks:
      - default

  nginx:
    image: nginx:1.24.0-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/nginx/pocketbase.conf:/etc/nginx/conf.d/pocketbase.conf"
      - "./logs:/var/log/nginx"
      - "./ssl:/etc/ssl:ro"
    networks:
      - default

networks:
  default:
    name: default-network
    driver: bridge
